name: viral_protein
description: small angle X-ray scattering information
required_metadata_keys:
- description: Identifier for Protein in CSBID
  key: protein_id
  required: true
  type: string
- description: Identifier for Virus in CSBID
  key: virus_id
  required: true
  type: string
